version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    working_directory: ~/lib-ledger-core
    steps:
      - checkout
      - run:
          command: |
            . .circleci/setup_debian.sh
      - run:
          name: git version
          command: git --version
      - run: git submodule init
      - run:
          command: |
            . .circleci/build_lib.sh
      - run:
          command: |
            . .circleci/logs.sh
      - run:
          name: build module
          command: yarn
      - run:
          name: test
          command: |
              node index.js && node sample/wallet_pool_test.js
      - run: |
    # tell the operating system to remove the file size limit on core dump files
          ulimit -c unlimited
          ./dump
      - run:
          command: |
            mkdir -p /tmp/core_dumps
            cp ./sample/tmp/database_test_instance /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps