version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    working_directory: ~/lib-ledger-core
    steps:
      - checkout
      - run:
          command: |
            . .circleci/setup_debian.sh
      - run:
          name: git version
          command: git --version
      - run: git submodule init
      - run:
          command: |
            . .circleci/build_lib.sh
      - run:
          command: |
            . .circleci/logs.sh
      - run:
          name: build module
          command: yarn
      - run:
          name: test
          command: |
              node index.js && node sample/wallet_pool_test.js
      - run:
          command: |
              mkdir -p /tmp/core_dumps
              cp ./sample/tmp/log_file_test_instance-l.log /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps
      - run:
          command: |
              mkdir -p /tmp/lib
              cp ../lib-ledger-core-build/core/src/libledger-core.so /tmp/lib
      - store_artifacts:
          path: /tmp/lib
      - run:
          command: |
              mkdir -p /tmp/node_module
              cp ./build/Release/ledgerapp_nodejs.node /tmp/node_module
      - store_artifacts:
          path: /tmp/node_module