version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    working_directory: ~/lib-ledger-core
    steps:
      - checkout
      - run:
          command: |
            . .circleci/setup_debian.sh
      - run:
          name: git version
          command: git --version
      - run: git submodule init
      - run:
          name: create build directory
          command: cd .. && mkdir lib-ledger-core-build
      - run:
          name: build
          command: cd lib-ledger-core-build && pwd && cmake -DCMAKE_INSTALL_PREFIX=/root ../lib-ledger-core && make
      - run:
          name: build module
          command: yarn
      - run:
          name: test
          command: node index.js