version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - type: shell
              shell: /bin/sh
              pwd: /
              command: apk -U add git openssh
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: qt5
          command: wget http://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run
      - run:
          name: create build directory
          command: cd .. && mkdir lib-ledger-core-build && cd lib-ledger-core-build
      - run:
          name: build
          command: cmake -DCMAKE_INSTALL_PREFIX=/usr/lib ../lib-ledger-core && make
      - run:
          name: build module
          command: yarn
      - run:
          name: test
          command: node index.js